# ENTREGABLE SQL - Estefania Escribano Bernard
IMPORTANTE: Debido a que no pude resolver un error recurrente al querer importar las tablas de excel a SQL, procedió a convertir los archivos originales a formato CSV. De esta forma me funcionó. 
1. Conexión

In [56]:
!pip install sqlalchemy
!pip install mysql-connector-python

Requirement already satisfied: sqlalchemy in c:\users\user\anaconda3\envs\clasenucliosql\lib\site-packages (1.4.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\user\anaconda3\envs\clasenucliosql\lib\site-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: mysql-connector-python in c:\users\user\anaconda3\envs\clasenucliosql\lib\site-packages (8.0.33)
Requirement already satisfied: protobuf<=3.20.3,>=3.11.0 in c:\users\user\anaconda3\envs\clasenucliosql\lib\site-packages (from mysql-connector-python) (3.20.3)

In [1]:
from sqlalchemy import create_engine
import sqlalchemy
import mysql.connector as mysql
import pandas as pd

In [2]:
# Parámetros de conexión
user     = 'root'
password = 'Baloo.sql.93'
#db = ''
sqlServer = 'localhost' # debería ser IP o DNS (Domain Name System) del servidor de la base de datos

# Creamos string de conexión
connStr = "mysql+mysqlconnector://" + user + ":" + password + "@" + sqlServer # +  "/"  + db

# print de string de conexión
print (connStr)

# Conectamos con el servidor
conn = create_engine(connStr).connect()

mysql+mysqlconnector://root:Baloo.sql.93@localhost

In [3]:
sSQL="USE NUCLIO"
conn.execute(sSQL)

# Creacion de tablas

In [60]:
ALOJAMIENTO=pd.read_csv("ALOJAMIENTO.csv", sep=',')
ALOJAMIENTO

,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,ALOJ002,Apartamento Las Palmeras,1,2,SI,NO,SI,NO,75
2,ALOJ003,Cabaña El Refugio,1,1,NO,SI,NO,NO,45
3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
4,ALOJ005,Estudio Playa Blanca,1,1,NO,NO,SI,NO,40
5,ALOJ006,Chalet Vista al Lago,3,4,SI,SI,SI,SI,150
6,ALOJ007,Dúplex Jardines del Sur,2,3,SI,SI,SI,SI,130
7,ALOJ008,Loft Urbano,1,1,SI,NO,SI,NO,60
8,ALOJ009,Casa Rústica Montaña,2,2,SI,SI,NO,NO,85
9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88
10,ALOJ011,Cabaña Bosque Encantado,1,2,NO,SI,NO,NO,65
11,ALOJ012,Villa Palmeras,2,3,SI,SI,SI,SI,110
12,ALOJ013,Apartamento Moderno,1,2,SI,NO,SI,NO,80
13,ALOJ014,Casa del Mar,3,4,SI,SI,SI,SI,160
14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120
15,ALOJ016,Estudio Urbano,1,1,NO,NO,SI,NO,35
16,ALOJ017,Chalet Jardín Secreto,3,5,SI,SI,SI,SI,180
17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100
18,ALOJ019,Casa Río Claro,2,2,SI,SI,NO,NO,95
19,ALOJ020,Loft Estación Norte,1,1,SI,NO,SI,NO,55

In [61]:
ALOJAMIENTO.to_sql('alojamiento1', conn)

ProgrammingError: (mysql.connector.errors.ProgrammingError) 1050 (42S01): Table 'alojamiento1' already exists
[SQL:
CREATE TABLE alojamiento1 (
	`index` BIGINT,
	`CODIGO_ALOJAMIENTO` TEXT,
	`NOMBRE` TEXT,
	`CANT_BANYOS` BIGINT,
	`CANT_HAB` BIGINT,
	`SALON` TEXT,
	`TERRAZA` TEXT,
	`AIREC_ACOND` TEXT,
	`PISCINA` TEXT,
	`SUPERFICIE` BIGINT
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [ ]:
UBICACION=pd.read_csv("UBICACION.csv", sep=',')
UBICACION

   CODIGO_ALOJAMIENTO      PAIS     CIUDAD  DIST_METRO  DIST_CENTRO
0             ALOJ001  Portugal      Liboa         1.0          2.0
1             ALOJ002    España     Madrid         0.5          0.8
2             ALOJ003    España  Barcelona         0.9          0.4
3             ALOJ004   Francia   Marsella         3.0          4.0
4             ALOJ005  Portugal     Oporto         4.0          3.0
5             ALOJ006   Francia      Paris         2.0          2.0
6             ALOJ007   Francia   Toulouse         1.0          3.0
7             ALOJ008    España  Barcelona         2.0          3.0
8             ALOJ009    España     Madrid         2.0          4.0
9             ALOJ010    España     Bilbao         2.0          5.0
10            ALOJ011    Italia      Milan         0.5          0.7
11            ALOJ012    Italia       Roma         1.0          0.8
12            ALOJ013    España    Sevilla         2.0          0.9
13            ALOJ014    Italia   Cerdegna         0.9          4.0
14            ALOJ015    España     Málaga         2.0          4.0
15            ALOJ016    Italia       Roma         2.0          2.0
16            ALOJ017   Francia      Paris         1.0          2.0
17            ALOJ018    España      Ibiza         2.0          4.0
18            ALOJ019  Portugal      Lagos         2.0          2.0
19            ALOJ020  Portugal    Madeira         3.0          2.0

In [ ]:
UBICACION.to_sql('ubicacion1', conn)

20

In [ ]:
PRECIO=pd.read_csv("PRECIO.csv", sep=',')
PRECIO

   CODIGO_ALOJAMIENTO  PRECIO_ALQUILER RESERVA  PORCENTAJE_RESERVA
0             ALOJ001             1800      SI                 100
1             ALOJ002              780      SI                  25
2             ALOJ003              800      NO                   0
3             ALOJ004             1600      SI                  25
4             ALOJ005              900      NO                   0
5             ALOJ006             1200      NO                   0
6             ALOJ007             1300      NO                   0
7             ALOJ008             1500      SI                  25
8             ALOJ009             1600      SI                 100
9             ALOJ010             1750      SI                  25
10            ALOJ011             1825      NO                   0
11            ALOJ012             1750      NO                   0
12            ALOJ013             1652      NO                   0
13            ALOJ014             1941      NO                   0
14            ALOJ015             1800      SI                  25
15            ALOJ016             2000      SI                  30
16            ALOJ017             2120      NO                   0
17            ALOJ018             1900      SI                  25
18            ALOJ019             1570      NO                   0
19            ALOJ020             1580      NO                   0

In [ ]:
PRECIO.to_sql('precio1', conn)

20

In [ ]:
PUNTUACION=pd.read_csv("PUNTUACION.csv", sep=',')
PUNTUACION

,CODIGO_ALOJAMIENTO,PUNTOS,AGENCIA,PUNTOS_AGENCIA,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,ALOJ001,5.0,GlobalHome,4.4,NaN,NaN,NaN
1,ALOJ002,4.2,AndesRenta,4.1,NaN,NaN,NaN
2,ALOJ003,4.1,AlquilaFacil,4.0,NaN,NaN,NaN
3,ALOJ004,4.6,CaribeRent,4.6,NaN,NaN,NaN
4,ALOJ005,4.4,RentaTop,3.8,NaN,NaN,NaN
5,ALOJ006,4.3,TerraHouse,4.9,NaN,NaN,NaN
6,ALOJ007,4.9,SevillaRooms,4.5,NaN,NaN,NaN
7,ALOJ008,4.8,ChileVive,4.3,NaN,NaN,NaN
8,ALOJ009,4.7,MexicoRent,4.8,NaN,NaN,NaN
9,ALOJ010,4.8,UYAlquila,4.9,NaN,NaN,NaN
10,ALOJ011,4.0,MalagaTurismo,4.9,NaN,NaN,NaN
11,ALOJ012,4.2,CórdobaStay,4.6,NaN,NaN,NaN
12,ALOJ013,3.8,AndesElite,4.3,NaN,NaN,NaN
13,ALOJ014,4.7,BogotaLodge,4.5,NaN,NaN,NaN
14,ALOJ015,4.9,EasyStay Valencia,4.7,NaN,NaN,NaN
15,ALOJ016,4.3,PuntaAlquileres,4.4,NaN,NaN,NaN
16,ALOJ017,4.9,CuscoRenta,4.4,NaN,NaN,NaN
17,ALOJ018,4.7,MendozaRooms,4.7,NaN,NaN,NaN
18,ALOJ019,4.9,GDLRent,4.2,NaN,NaN,NaN
19,ALOJ020,4.9,VivaStay,4.9,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
PUNTUACION.to_sql('puntuacion1', conn)

44

In [4]:
sSQL="SHOW TABLES"
tables = conn.execute(sSQL)

In [5]:
tables.fetchall()

[('alojamiento1',),
 ('clientesv1',),
 ('corte_ingles',),
 ('customers',),
 ('planes1',),
 ('plantilla2',),
 ('precio1',),
 ('productos_mercadona',),
 ('products',),
 ('products_final',),
 ('proveedor',),
 ('puntuacion1',),
 ('sellers',),
 ('serjefe',),
 ('ubicacion',),
 ('ubicacion1',),
 ('ventas',)]

# PRIMERA PARTE
# PASO 1

# Creacion de queries segun exigencias del cliente

In [6]:
Ssql= "SHOW COLUMNS FROM alojamiento1"
conn.execute(Ssql).fetchall()

[('index', b'bigint', 'YES', 'MUL', None, ''),
 ('CODIGO_ALOJAMIENTO', b'text', 'YES', '', None, ''),
 ('NOMBRE', b'text', 'YES', '', None, ''),
 ('CANT_BANYOS', b'bigint', 'YES', '', None, ''),
 ('CANT_HAB', b'bigint', 'YES', '', None, ''),
 ('SALON', b'text', 'YES', '', None, ''),
 ('TERRAZA', b'text', 'YES', '', None, ''),
 ('AIREC_ACOND', b'text', 'YES', '', None, ''),
 ('PISCINA', b'text', 'YES', '', None, ''),
 ('SUPERFICIE', b'bigint', 'YES', '', None, '')]

In [7]:
#El cliente exige terraza y aire acondicionado, pero no quiere piscina.
sSQL = """
SELECT CODIGO_ALOJAMIENTO, NOMBRE
FROM alojamiento1
WHERE TERRAZA = 'SI'
AND AIREC_ACOND = 'SI'
AND PISCINA = 'NO'
"""

pd.read_sql(sSQL, conn)

  CODIGO_ALOJAMIENTO                 NOMBRE
0            ALOJ004  Piso Centro Histórico
1            ALOJ010          Ático del Sol
2            ALOJ015       Dúplex Las Rocas
3            ALOJ018    Piso Parque Central

In [8]:
# No se alojará en estudios que no tengan salón ni en propiedades con solo un baño
sSQL = """
SELECT CODIGO_ALOJAMIENTO, NOMBRE
FROM alojamiento1
WHERE SALON = 'SI'
AND CANT_BANYOS > 1
"""

pd.read_sql(sSQL, conn)

   CODIGO_ALOJAMIENTO                   NOMBRE
0             ALOJ001        Villa Sol del Mar
1             ALOJ004    Piso Centro Histórico
2             ALOJ006     Chalet Vista al Lago
3             ALOJ007  Dúplex Jardines del Sur
4             ALOJ009     Casa Rústica Montaña
5             ALOJ010            Ático del Sol
6             ALOJ012           Villa Palmeras
7             ALOJ014             Casa del Mar
8             ALOJ015         Dúplex Las Rocas
9             ALOJ017    Chalet Jardín Secreto
10            ALOJ018      Piso Parque Central
11            ALOJ019           Casa Río Claro

In [9]:
#La propiedad debe tener como mínimo 80m2
sSQL = """
SELECT CODIGO_ALOJAMIENTO, NOMBRE
FROM alojamiento1
WHERE SUPERFICIE > 80

"""

pd.read_sql(sSQL, conn)

   CODIGO_ALOJAMIENTO                   NOMBRE
0             ALOJ001        Villa Sol del Mar
1             ALOJ004    Piso Centro Histórico
2             ALOJ006     Chalet Vista al Lago
3             ALOJ007  Dúplex Jardines del Sur
4             ALOJ009     Casa Rústica Montaña
5             ALOJ010            Ático del Sol
6             ALOJ012           Villa Palmeras
7             ALOJ014             Casa del Mar
8             ALOJ015         Dúplex Las Rocas
9             ALOJ017    Chalet Jardín Secreto
10            ALOJ018      Piso Parque Central
11            ALOJ019           Casa Río Claro

In [10]:
#Como el cliente odia el ruido, no quiere alojarse en propiedades a menos de 1 km de una estación de metro ni a menos de 2 km del centro.
sSQL = """
SELECT 
    A.NOMBRE, 
    U.DIST_CENTRO, 
    U.DIST_METRO
FROM alojamiento1 AS A
JOIN ubicacion1 AS U 
    ON A.CODIGO_ALOJAMIENTO = U.CODIGO_ALOJAMIENTO
WHERE U.DIST_METRO >= 1 
  AND U.DIST_CENTRO >= 2;

"""

pd.read_sql(sSQL, conn)

                     NOMBRE  DIST_CENTRO  DIST_METRO
0         Villa Sol del Mar          2.0         1.0
1     Piso Centro Histórico          4.0         3.0
2      Estudio Playa Blanca          3.0         4.0
3      Chalet Vista al Lago          2.0         2.0
4   Dúplex Jardines del Sur          3.0         1.0
5               Loft Urbano          3.0         2.0
6      Casa Rústica Montaña          4.0         2.0
7             Ático del Sol          5.0         2.0
8          Dúplex Las Rocas          4.0         2.0
9            Estudio Urbano          2.0         2.0
10    Chalet Jardín Secreto          2.0         1.0
11      Piso Parque Central          4.0         2.0
12           Casa Río Claro          2.0         2.0
13      Loft Estación Norte          2.0         3.0

In [11]:
#El rango permitido por el cliente para pagar es entre 1.500€ y 2.000€ la noche.
sSQL = """
SELECT 
    A.NOMBRE, 
    P.PRECIO_ALQUILER
FROM alojamiento1 AS A
JOIN precio1 AS P 
    ON A.CODIGO_ALOJAMIENTO = P.CODIGO_ALOJAMIENTO
WHERE P.PRECIO_ALQUILER <= 2000 AND P.PRECIO_ALQUILER >= 1500;

"""

pd.read_sql(sSQL, conn)

                     NOMBRE  PRECIO_ALQUILER
0         Villa Sol del Mar             1800
1     Piso Centro Histórico             1600
2               Loft Urbano             1500
3      Casa Rústica Montaña             1600
4             Ático del Sol             1750
5   Cabaña Bosque Encantado             1825
6            Villa Palmeras             1750
7       Apartamento Moderno             1652
8              Casa del Mar             1941
9          Dúplex Las Rocas             1800
10           Estudio Urbano             2000
11      Piso Parque Central             1900
12           Casa Río Claro             1570
13      Loft Estación Norte             1580

In [12]:
#Como en anteriores ocasiones ha tenido problemas de intentos de estafas con
#otras agencias, el cliente pide que el % de reserva no sea muy alto, pero tampoco
#tan bajo (porque le genera inseguridad) por lo que propone un 25%

sSQL = """
SELECT 
    A.NOMBRE, 
    P.PORCENTAJE_RESERVA
FROM alojamiento1 AS A
JOIN precio1 AS P 
    ON A.CODIGO_ALOJAMIENTO = P.CODIGO_ALOJAMIENTO
WHERE P.PORCENTAJE_RESERVA = 25;

"""

pd.read_sql(sSQL, conn)

                     NOMBRE  PORCENTAJE_RESERVA
0  Apartamento Las Palmeras                  25
1     Piso Centro Histórico                  25
2               Loft Urbano                  25
3             Ático del Sol                  25
4          Dúplex Las Rocas                  25
5       Piso Parque Central                  25

In [13]:
Ssql= "SHOW COLUMNS FROM puntuacion1"
conn.execute(Ssql).fetchall()

[('index', b'bigint', 'YES', 'MUL', None, ''),
 ('CODIGO_ALOJAMIENTO', b'text', 'YES', '', None, ''),
 ('PUNTOS', b'double', 'YES', '', None, ''),
 ('AGENCIA', b'text', 'YES', '', None, ''),
 ('PUNTOS_AGENCIA', b'double', 'YES', '', None, ''),
 ('Unnamed: 4', b'double', 'YES', '', None, ''),
 ('Unnamed: 5', b'double', 'YES', '', None, ''),
 ('Unnamed: 6', b'double', 'YES', '', None, '')]

In [14]:
#Quiere que el alojamiento tenga más de 4,5 puntos de confianza 
# y que la agencia que lo lleva tenga más de 4 puntos
sSQL = """
SELECT 
    A.NOMBRE, 
    PN.PUNTOS,
    PN.PUNTOS_AGENCIA
FROM alojamiento1 AS A
JOIN puntuacion1 AS PN 
    ON A.CODIGO_ALOJAMIENTO = PN.CODIGO_ALOJAMIENTO
WHERE PN.PUNTOS > 4.5 AND PN.PUNTOS_AGENCIA > 4
"""

pd.read_sql(sSQL, conn)

                     NOMBRE  PUNTOS  PUNTOS_AGENCIA
0         Villa Sol del Mar     5.0             4.4
1     Piso Centro Histórico     4.6             4.6
2   Dúplex Jardines del Sur     4.9             4.5
3               Loft Urbano     4.8             4.3
4      Casa Rústica Montaña     4.7             4.8
5             Ático del Sol     4.8             4.9
6              Casa del Mar     4.7             4.5
7          Dúplex Las Rocas     4.9             4.7
8     Chalet Jardín Secreto     4.9             4.4
9       Piso Parque Central     4.7             4.7
10           Casa Río Claro     4.9             4.2
11      Loft Estación Norte     4.9             4.9

# PASO 2
Crear en una única query la combinación de los filtros anteriores para
hallar las propiedades que finalmente cumplen con todas las exigencias del cliente.

In [ ]:
sSQL = """
SELECT 
    A.NOMBRE,
    A.CODIGO_ALOJAMIENTO,
    P.PRECIO_ALQUILER,
    PN.PUNTOS AS PUNTUACION_TOTAL
FROM alojamiento1 AS A
JOIN ubicacion1 AS U 
    ON A.CODIGO_ALOJAMIENTO = U.CODIGO_ALOJAMIENTO

JOIN precio1 AS P 
    ON A.CODIGO_ALOJAMIENTO = P.CODIGO_ALOJAMIENTO

JOIN puntuacion1 AS PN 
    ON A.CODIGO_ALOJAMIENTO = PN.CODIGO_ALOJAMIENTO

WHERE 
    A.TERRAZA = 'SI' 
    AND A.AIREC_ACOND = 'SI' 
    AND A.PISCINA = 'NO'
    AND A.SALON = 'SI'
    AND A.CANT_BANYOS > 1
    AND A.SUPERFICIE > 80

    AND U.DIST_METRO >= 1
    AND U.DIST_CENTRO >= 2 

    AND P.PRECIO_ALQUILER BETWEEN 1500 AND 2000
    AND P.PORCENTAJE_RESERVA = 25   

    AND PN.PUNTOS > 4.5 
    AND PN.PUNTOS_AGENCIA > 4;
"""
pd.read_sql(sSQL, conn)

                  NOMBRE CODIGO_ALOJAMIENTO  PRECIO_ALQUILER  PUNTUACION_TOTAL
0  Piso Centro Histórico            ALOJ004             1600               4.6
1          Ático del Sol            ALOJ010             1750               4.8
2       Dúplex Las Rocas            ALOJ015             1800               4.9
3    Piso Parque Central            ALOJ018             1900               4.7

# PASO 3
Como habéis visto, tenemos 4 propiedades que cumplen con todas las
exigencias de nuestro cliente, ahora bien, desde tu punto de vista, haciendo un análisis de
los datos del cliente y de todas sus exigencias ¿Cuál de estos 4 alojamientos le
recomendarías y por qué?

In [ ]:
sSQL = """
SELECT 
    A.NOMBRE,
    P.PRECIO_ALQUILER,
    A.CANT_BANYOS,
    A.SUPERFICIE,
    PN.PUNTOS,
    PN.PUNTOS_AGENCIA,
    PN.PUNTOS AS PUNTUACION_TOTAL
FROM alojamiento1 AS A
JOIN ubicacion1 AS U 
    ON A.CODIGO_ALOJAMIENTO = U.CODIGO_ALOJAMIENTO

JOIN precio1 AS P 
    ON A.CODIGO_ALOJAMIENTO = P.CODIGO_ALOJAMIENTO

JOIN puntuacion1 AS PN 
    ON A.CODIGO_ALOJAMIENTO = PN.CODIGO_ALOJAMIENTO

WHERE 
    A.TERRAZA = 'SI' 
    AND A.AIREC_ACOND = 'SI' 
    AND A.PISCINA = 'NO'
    AND A.SALON = 'SI'
    AND A.CANT_BANYOS > 1
    AND A.SUPERFICIE > 80

    AND U.DIST_METRO >= 1
    AND U.DIST_CENTRO >= 2 

    AND P.PRECIO_ALQUILER BETWEEN 1500 AND 2000
    AND P.PORCENTAJE_RESERVA = 25   

    AND PN.PUNTOS > 4.5 
    AND PN.PUNTOS_AGENCIA > 4;
"""
pd.read_sql(sSQL, conn)

,NOMBRE,PRECIO_ALQUILER,CANT_BANYOS,SUPERFICIE,PUNTOS,PUNTOS_AGENCIA,PUNTUACION_TOTAL
0,Piso Centro Histórico,1600,2,90,4.6,4.6,4.6
1,Ático del Sol,1750,3,88,4.8,4.9,4.8
2,Dúplex Las Rocas,1800,3,120,4.9,4.7,4.9
3,Piso Parque Central,1900,2,100,4.7,4.7,4.7

Considerando las 4 opciones, recomendaria el Dúplex Las Rocas. Este alojamiento es el tiene la mayor puntuacion (tanto por el alojamiento como por la agencia) y no es el mas costoso. Adicionalmente, tiene 3 baños y 120M2 proporcionando un mayor confort al ser una familia numerosa.

# SEGUNDA PARTE

1. ¿Cuál es la suma total de metros cuadrados de los alojamientos que tienen piscina?

In [ ]:
sSQL = """
SELECT SUM(SUPERFICIE) AS TOTAL_M2_PISCINA
FROM alojamiento1
WHERE PISCINA = "SI";
"""

df_final = pd.read_sql(sSQL, conn)
print(f"La suma total de metros cuadrados de los alojamientos con piscina es:")
df_final

La suma total de metros cuadrados de los alojamientos con piscina es:

   TOTAL_M2_PISCINA
0             850.0

2. ¿Cuál es el alojamiento con mayor superficie?

In [ ]:
sSQL = """
SELECT NOMBRE, SUPERFICIE
FROM alojamiento1
ORDER BY SUPERFICIE DESC
LIMIT 1;
"""
pd.read_sql(sSQL, conn)

                  NOMBRE  SUPERFICIE
0  Chalet Jardín Secreto         180

3.¿Cuál es el alojamiento con menor superficie?

In [ ]:
sSQL = """
SELECT NOMBRE, SUPERFICIE
FROM alojamiento1
ORDER BY SUPERFICIE ASC
LIMIT 1;
"""
pd.read_sql(sSQL, conn)

           NOMBRE  SUPERFICIE
0  Estudio Urbano          35

4. ¿Cuántos alojamientos tienen salón?

In [ ]:
sSQL = """
SELECT COUNT(*) AS TOT_ALOJ_SALON
FROM alojamiento1
WHERE SALON = "SI";
"""

pd.read_sql(sSQL, conn)

   TOT_ALOJ_SALON
0              16

5.¿Cuántos alojamientos tienen terraza?

In [ ]:
sSQL = """
SELECT COUNT(*) AS TOT_ALOJ_TERRAZ
FROM alojamiento1
WHERE TERRAZA = "SI";
"""
pd.read_sql(sSQL, conn)

   TOT_ALOJ_TERRAZ
0               14

6. ¿Cuántos alojamientos hay por cada país según nuestra tabla de UBICACIÓN?

In [ ]:
sSQL = """
SELECT PAIS, COUNT(*) AS TOTAL_ALOJ
FROM ubicacion1
GROUP BY PAIS
ORDER BY TOTAL_ALOJ DESC;
"""
pd.read_sql(sSQL, conn)

       PAIS  TOTAL_ALOJ
0    España           8
1  Portugal           4
2   Francia           4
3    Italia           4

7. ¿Cuál es el promedio de precios de alquiler de todos los alojamientos según la
tabla PRECIO?

In [31]:
sSQL = """
SELECT AVG(PRECIO_ALQUILER) AS Precio_promedio
FROM precio1;
"""

pd.read_sql(sSQL, conn)

   Precio_promedio
0           1568.4

8.¿Cuáles son las 3 agencias que tienen la mayor puntuación de agencia (campo a
usar: PUNTOS_AGENCIA) según la tabla PUNTUACION?

In [ ]:
sSQL = """
SELECT AGENCIA, PUNTOS_AGENCIA
FROM puntuacion1
ORDER BY PUNTOS_AGENCIA DESC
LIMIT 3;
"""
pd.read_sql(sSQL, conn)

         AGENCIA  PUNTOS_AGENCIA
0     TerraHouse             4.9
1  MalagaTurismo             4.9
2      UYAlquila             4.9

9. Muestra los alojamientos (código y nombre) que: Contengan la palabra ‘Piso’ en su
nombre o que tengan piscina y aire acondicionado, pero no pasen los 150 metros
de superficie o que tengan más de un baño

In [ ]:
sSQL = """
SELECT CODIGO_ALOJAMIENTO, NOMBRE 
FROM alojamiento1
WHERE NOMBRE LIKE"%Piso%"
OR PISCINA="SI" AND AIREC_ACOND="SI" AND SUPERFICIE <= 150
OR CANT_BANYOS<1;
"""
pd.read_sql(sSQL, conn)

  CODIGO_ALOJAMIENTO                   NOMBRE
0            ALOJ001        Villa Sol del Mar
1            ALOJ004    Piso Centro Histórico
2            ALOJ006     Chalet Vista al Lago
3            ALOJ007  Dúplex Jardines del Sur
4            ALOJ012           Villa Palmeras
5            ALOJ018      Piso Parque Central

10. Muestra una consulta que muestre el código de alojamiento, el nombre, el precio y
una columna donde veamos el precio del alquiler con el símbolo del euro al final de
cada importe, esta nueva columna se debe llama PRECIO_MODIF

In [ ]:
sSQL = """
SELECT 
    A.CODIGO_ALOJAMIENTO,
    A.NOMBRE, 
    P.PRECIO_ALQUILER,
    CONCAT(P.PRECIO_ALQUILER,' €') AS PRECIO_MODIF
FROM alojamiento1 AS A
JOIN precio1 AS P 
    ON A.CODIGO_ALOJAMIENTO = P.CODIGO_ALOJAMIENTO;
"""
pd.read_sql(sSQL, conn)

   CODIGO_ALOJAMIENTO                    NOMBRE  PRECIO_ALQUILER PRECIO_MODIF
0             ALOJ001         Villa Sol del Mar             1800       1800 €
1             ALOJ002  Apartamento Las Palmeras              780        780 €
2             ALOJ003         Cabaña El Refugio              800        800 €
3             ALOJ004     Piso Centro Histórico             1600       1600 €
4             ALOJ005      Estudio Playa Blanca              900        900 €
5             ALOJ006      Chalet Vista al Lago             1200       1200 €
6             ALOJ007   Dúplex Jardines del Sur             1300       1300 €
7             ALOJ008               Loft Urbano             1500       1500 €
8             ALOJ009      Casa Rústica Montaña             1600       1600 €
9             ALOJ010             Ático del Sol             1750       1750 €
10            ALOJ011   Cabaña Bosque Encantado             1825       1825 €
11            ALOJ012            Villa Palmeras             1750       1750 €
12            ALOJ013       Apartamento Moderno             1652       1652 €
13            ALOJ014              Casa del Mar             1941       1941 €
14            ALOJ015          Dúplex Las Rocas             1800       1800 €
15            ALOJ016            Estudio Urbano             2000       2000 €
16            ALOJ017     Chalet Jardín Secreto             2120       2120 €
17            ALOJ018       Piso Parque Central             1900       1900 €
18            ALOJ019            Casa Río Claro             1570       1570 €
19            ALOJ020       Loft Estación Norte             1580       1580 €

11. Muestra una columna sobre la tabla PRECIO que se llame CATEGORIA_PRECIO y
que indique la palabra ‘Bajo’ si el precio está entre 780 y 1000, ‘Medio’ si el precio
está entre 1000 y 1700 y ‘Alto’ si es mayor a 1700

In [ ]:
sSQL = """
SELECT 
    CODIGO_ALOJAMIENTO,
    PRECIO_ALQUILER, 
    CASE
        WHEN PRECIO_ALQUILER BETWEEN 780 and 1000 THEN "Bajo"
        WHEN PRECIO_ALQUILER BETWEEN 1000 and 1700 THEN "Medio"
        WHEN PRECIO_ALQUILER >1700 THEN "Alto"
    END AS CATEGORIA_PRECIO
  
FROM precio1
ORDER BY PRECIO_ALQUILER DESC;
"""
pd.read_sql(sSQL, conn)

   CODIGO_ALOJAMIENTO  PRECIO_ALQUILER CATEGORIA_PRECIO
0             ALOJ017             2120             Alto
1             ALOJ016             2000             Alto
2             ALOJ014             1941             Alto
3             ALOJ018             1900             Alto
4             ALOJ011             1825             Alto
5             ALOJ001             1800             Alto
6             ALOJ015             1800             Alto
7             ALOJ010             1750             Alto
8             ALOJ012             1750             Alto
9             ALOJ013             1652            Medio
10            ALOJ004             1600            Medio
11            ALOJ009             1600            Medio
12            ALOJ020             1580            Medio
13            ALOJ019             1570            Medio
14            ALOJ008             1500            Medio
15            ALOJ007             1300            Medio
16            ALOJ006             1200            Medio
17            ALOJ005              900             Bajo
18            ALOJ003              800             Bajo
19            ALOJ002              780             Bajo