# Assignment Final
Los datos que se incluyen en el fichero `datos_ventas_centros_comerciales.csv` representan casi 100.000 compra-ventas realizadas en un grupo de Centros Comerciales de Turquía durante un conjunto de años. 

Como analista del holding propietario de los centros comerciales, realiza un análisis respondiendo a las siguientes preguntas.  

## Notas y consejos

> **Consejo 1:** Es buena práctica, especialmente en preguntas que piden "el que más" o "el que menos" de algo,  
> considerar que puede haber **más de un valor máximo o mínimo** y decidir si devolverlo como **una colección de elementos** en lugar de un único valor.  

> **Consejo 2:** Solo es obligatorio crear una función cuando la pregunta lo indique explícitamente.  
> Sin embargo, te animo a crear funciones para organizar tu código y reutilizarlo cuando tenga sentido.  

> **Consejo 3:** Algunas preguntas se pueden resolver de manera muy similar, cambiando solo pequeños detalles del código.  
> Te invito a que, si notas que una solución se parece mucho a otra, pienses en **formas alternativas** de resolverla.

> **Consejo 4:** Antes de entregar, **reinicia el kernel y ejecuta todas las celdas** (`Restart Kernel + Run All`)  
> para asegurarte de que todo el código funciona correctamente desde cero.  
> Si alguna celda no se ejecuta correctamente, el ejercicio se calificará con un **máximo del 50%**.

### Definiciones de columnas del dataset

| Columna        | Descripción                                                                 |
|----------------|-----------------------------------------------------------------------------|
| invoice_no     | Número de factura. Una combinación de la letra 'I' y un número de 6 dígitos que identifica cada operación. |
| customer_id    | Número de cliente. Una combinación de la letra 'C' y un número de 6 dígitos que identifica a cada cliente. |
| category       | Categoría del producto comprado.                                            |
| quantity       | Cantidad de artículos comprados en la transacción.                          |
| price          | Precio unitario del producto en liras turcas (TL).                          |
| invoice_date   | Fecha en que se realizó la transacción.                                     |
| shopping_mall  | Nombre del centro comercial donde se realizó la compra.                     |

**Aclaración:** En las preguntas posteriores hay una diferencia importante entre **ingresos** y **número de ventas**.  
- **Ingresos**: se calculan multiplicando la cantidad (`quantity`) por el precio (`price`) de cada transacción.  
- **Número de ventas**: simplemente cuenta cuántas transacciones o facturas se realizaron, sin tener en cuenta el importe.

# 0. Exploración de Datos

Leer el CSV con pandas y explorar la información básica.

1. Cargar el CSV en una variable `datos`.

In [1]:
import pandas as pd

datos = pd.read_csv(r"c:\Users\User\Desktop\Python\entregable_1_python\datos\datos_ventas_centros_comerciales.csv")

2. Mostrar las primeras 5 filas y la información de las columnas.

In [2]:
datos.head(6)
#Incluyendo los titulos y las primeras 5 filas que contienen informacion

,invoice_no,customer_id,category,quantity,price,invoice_date,shopping_mall
0,I138884,C241288,Clothing,5,8172.24,05-08-2022,Kanyon
1,I317333,C111565,Shoes,3,8868.64,12-12-2021,Forum Istanbul
2,I127801,C266599,Clothing,1,4863.95,09-11-2021,Metrocity
3,I173702,C988172,Shoes,5,711.48,16-05-2021,Metropol AVM
4,I337046,C189076,Books,4,1110.32,24-10-2021,Kanyon
5,I227836,C657758,Clothing,5,869.43,24-05-2022,Forum Istanbul

3. Contar el número de filas y columnas.

In [3]:
datos.shape
print("Son 99457 filas y 7 columnas")

Son 99457 filas y 7 columnas

4. Mostrar los nombres de todas las columnas disponibles.

In [4]:
datos.head(0)

Empty DataFrame
Columns: [invoice_no, customer_id, category, quantity, price, invoice_date, shopping_mall]
Index: []

5. ¿Hay alguna columna con datos faltantes?  Si es así, ¿cuántos datos faltan por columna?  

Borra las filas que tengan algún dato faltante y vuelve a contar cuántas filas quedan.

In [5]:
#Cuantas colunas con datos faltantes hay:
control_columnas= datos.isnull().sum()

if control_columnas.empty:
    print("Las siguientes columnas tienen datos faltantes:")
    print(control_columnas)
else:
    print("No existen datos faltantes.")

No existen datos faltantes.

6. Convertir `invoice_date` a tipo datetime y verificar que el cambio se realizó correctamente.

In [6]:
print(datos.info())
#la columna es del tipo object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   invoice_no     99457 non-null  object
 1   customer_id    99457 non-null  object
 2   category       99457 non-null  object
 3   quantity       99457 non-null  int64
 4   price          99457 non-null  float64
 5   invoice_date   99457 non-null  object
 6   shopping_mall  99457 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 5.3+ MB
None

In [7]:
#Algunas fechas estan en otro formato, las convertimos todas al mismo:
datos['invoice_date'] = datos['invoice_date'].astype(str)

In [8]:
datos['invoice_date'] = pd.to_datetime(datos['invoice_date'], errors='coerce')

In [9]:
print(datos.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   invoice_no     99457 non-null  object
 1   customer_id    99457 non-null  object
 2   category       99457 non-null  object
 3   quantity       99457 non-null  int64
 4   price          99457 non-null  float64
 5   invoice_date   40029 non-null  datetime64[ns]
 6   shopping_mall  99457 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 5.3+ MB
None

7. Explora alguna otra característica del dataset que consideres relevante.  
   *Os dejo algunos ejemplos para que podáis inspiraros: categorías, centros comerciales o rangos de precios. Estos ejemplos no cuentan.*

In [10]:
#Que cliente compro mayor cantidad de productos?
top_client= datos.groupby("customer_id")["quantity"].sum().sort_values(ascending=False)
print(top_client)
print("El podio de clientes con mayores compras es:")
print(top_client.head(3))

customer_id
C100004    5
C211342    5
C154312    5
C324260    5
C211345    5
          ..
C195813    1
C195815    1
C593151    1
C593101    1
C205421    1
Name: quantity, Length: 99457, dtype: int64
El podio de clientes con mayores compras es:
customer_id
C100004    5
C211342    5
C154312    5
Name: quantity, dtype: int64

# 1. ¿Cuál es el total de ingresos generados por todas las ventas registradas?

Usa una función y opcionalmente guardar en `src/utils.py`.

Guarda el resultado en una variable llamada `total_ingresos`

In [11]:
total_ingresos = datos['quantity']*datos["price"] 
print(total_ingresos)

0        40861.20
1        26605.92
2         4863.95
3         3557.40
4         4441.28
           ...
99452    33462.10
99453    16794.48
99454     6506.54
99455    26505.64
99456    18674.16
Length: 99457, dtype: float64

In [12]:
datos["total_ingresos"] = datos['quantity']*datos["price"] 
print(datos)

      invoice_no customer_id         category  quantity    price invoice_date  \
0        I138884     C241288         Clothing         5  8172.24   2022-05-08
1        I317333     C111565            Shoes         3  8868.64   2021-12-12
2        I127801     C266599         Clothing         1  4863.95   2021-09-11
3        I173702     C988172            Shoes         5   711.48          NaT
4        I337046     C189076            Books         4  1110.32          NaT
...          ...         ...              ...       ...      ...          ...
99452    I219422     C441542         Souvenir         5  6692.42          NaT
99453    I325143     C569580  Food & Beverage         2  8397.24          NaT
99454    I824010     C103292  Food & Beverage         2  3253.27          NaT
99455    I702964     C800631       Technology         4  6626.41          NaT
99456    I232867     C273973         Souvenir         3  6224.72          NaT

          shopping_mall  total_ingresos
0                Kanyon        40861.20
1        Forum Istanbul        26605.92
2             Metrocity         4863.95
3          Metropol AVM         3557.40
4                Kanyon         4441.28
...                 ...             ...
99452            Kanyon        33462.10
99453    Forum Istanbul        16794.48
99454         Metrocity         6506.54
99455      Istinye Park        26505.64
99456  Mall of Istanbul        18674.16

[99457 rows x 8 columns]

# 2. ¿Cuál es el centro comercial que ha generado más ventas?
Usa una función y opcionalmente guardar en `src/utils.py`.

Guarda el resultado en una variable llamada `centro_comercial_mas_ventas`

In [13]:
tot_fact_por_centro = datos.groupby("shopping_mall")["total_ingresos"].sum()
print(tot_fact_por_centro)

shopping_mall
Cevahir AVM          7.369621e+07
Emaar Square Mall    7.311491e+07
Forum Istanbul       7.444548e+07
Istinye Park         1.478885e+08
Kanyon               2.966126e+08
Mall of Istanbul     2.987439e+08
Metrocity            2.240598e+08
Metropol AVM         1.518731e+08
Viaport Outlet       7.343815e+07
Zorlu Center         7.704880e+07
Name: total_ingresos, dtype: float64

In [14]:
centro_comercial_mas_ventas= tot_fact_por_centro.idxmax()
print(centro_comercial_mas_ventas)

Mall of Istanbul

# 3. ¿Cuál es la categoría de producto que ha generado mas ventas? 
Guarda el resultado en una variable llamada `categoria_mas_vendida`

In [15]:
category_tot = datos.groupby("category")["total_ingresos"].sum().sort_values(ascending=False)
print(category_tot)

category
Clothing           5.144041e+08
Cosmetics          2.269621e+08
Food & Beverage    2.223848e+08
Shoes              1.516301e+08
Toys               1.514814e+08
Technology         7.546344e+07
Books              7.442603e+07
Souvenir           7.416955e+07
Name: total_ingresos, dtype: float64

In [16]:
print("La categorina que mas vende es:")
print(category_tot.head(1))

La categorina que mas vende es:
category
Clothing    5.144041e+08
Name: total_ingresos, dtype: float64

# 4. ¿Cuál es el producto más caro vendido?
Guarda el resultado en una variable llamada `categoria_producto_mas_caro`

In [17]:
categoria_productos = datos.groupby("category")["price"].max()
print(categoria_productos)

category
Books              9997.05
Clothing           9999.60
Cosmetics          9999.10
Food & Beverage    9998.68
Shoes              9997.56
Souvenir           9999.48
Technology         9997.64
Toys               9999.85
Name: price, dtype: float64

In [18]:
categoria_producto_mas_caro= categoria_productos.idxmax()
print("El producto mas caro es:",categoria_producto_mas_caro)

El producto mas caro es: Toys

# 5. ¿Cuál es la factura más antigua registrada en el dataset?
Guarda el resultado en una variable llamada `factura_mas_antigua`.

In [19]:
factura_mas_antigua = datos["invoice_date"].min()
print(factura_mas_antigua,"es la factura mas antigua de la base")

2021-01-01 00:00:00 es la factura mas antigua de la base

# 6. ¿Cuál es la cantidad promedio de productos vendidos por transacción?
Guarda el resultado en una variable llamada `cantidad_promedio_por_transaccion`

In [20]:
cantidad_promedio_por_transaccion= datos["quantity"].mean()
print("Cantidad promedio de productos por transacción:", cantidad_promedio_por_transaccion)

Cantidad promedio de productos por transacción: 3.003428617392441

# 7. ¿Cuál es el día con más ventas registradas?
Guarda el resultado en una variable llamada `dia_con_mas_ventas`.

In [21]:
print(datos)

      invoice_no customer_id         category  quantity    price invoice_date  \
0        I138884     C241288         Clothing         5  8172.24   2022-05-08
1        I317333     C111565            Shoes         3  8868.64   2021-12-12
2        I127801     C266599         Clothing         1  4863.95   2021-09-11
3        I173702     C988172            Shoes         5   711.48          NaT
4        I337046     C189076            Books         4  1110.32          NaT
...          ...         ...              ...       ...      ...          ...
99452    I219422     C441542         Souvenir         5  6692.42          NaT
99453    I325143     C569580  Food & Beverage         2  8397.24          NaT
99454    I824010     C103292  Food & Beverage         2  3253.27          NaT
99455    I702964     C800631       Technology         4  6626.41          NaT
99456    I232867     C273973         Souvenir         3  6224.72          NaT

          shopping_mall  total_ingresos
0                Kanyon        40861.20
1        Forum Istanbul        26605.92
2             Metrocity         4863.95
3          Metropol AVM         3557.40
4                Kanyon         4441.28
...                 ...             ...
99452            Kanyon        33462.10
99453    Forum Istanbul        16794.48
99454         Metrocity         6506.54
99455      Istinye Park        26505.64
99456  Mall of Istanbul        18674.16

[99457 rows x 8 columns]

In [22]:
ventas_por_dia=datos["invoice_date"].value_counts().sort_values(ascending=False)
dia_con_mas_ventas= ventas_por_dia.index[0]
print("El dia con mas ventas es:", dia_con_mas_ventas)

El dia con mas ventas es: 2021-06-01 00:00:00

# 8. ¿Cuál es el cliente que más ha gastado en total?
Guarda el resultado en una variable llamada `cliente_que_mas_gasto`

In [23]:
gasto_cliente= datos.groupby("customer_id")["total_ingresos"].sum().sort_values(ascending=False)
cliente_que_mas_gasto= gasto_cliente.index[0]
print(cliente_que_mas_gasto, "es nuestro cliente estrella")

C307063 es nuestro cliente estrella

# 9. ¿Cuál es la factura con el precio total más alto?
Guarda el resultado en una variable llamada `factura_max_valor`

In [24]:
factura_max_valor= datos.sort_values(by="total_ingresos",ascending=False).iloc[0]
print("La factura con mayor valor es:", factura_max_valor)

La factura con mayor valor es: invoice_no          I311640
customer_id         C307063
category           Clothing
quantity                  5
price                9999.6
invoice_date            NaT
shopping_mall     Metrocity
total_ingresos      49998.0
Name: 17110, dtype: object

# 10. ¿Cuál es la distribución porcentual de ventas por categoría de producto?
Guarda el resultado en una variable llamada `distribucion_porcentual_ventas_por_categoria`. 

El tipo de `distribucion_porcentual_ventas_por_categoria` debe ser `pandas.core.series.Series` donde las etiquetas deben ser las categorias y los valores deben ser la distribucion porcentual de las ventas por categoría

In [25]:
distribucion_porcentual_ventas_por_categoria = (datos.groupby("category")["total_ingresos"].sum() / datos["total_ingresos"].sum())*100
distribucion_porcentual_ventas_por_categoria=distribucion_porcentual_ventas_por_categoria.round(0)
print("La distribucion procentual de ventas totales por categoria:",distribucion_porcentual_ventas_por_categoria)

La distribucion procentual de ventas totales por categoria: category
Books               5.0
Clothing           35.0
Cosmetics          15.0
Food & Beverage    15.0
Shoes              10.0
Souvenir            5.0
Technology          5.0
Toys               10.0
Name: total_ingresos, dtype: float64

In [26]:
print(type(distribucion_porcentual_ventas_por_categoria))

<class 'pandas.core.series.Series'>

# 11. ¿Cuál es el día de la semana con más ventas registradas en cada centro comercial?
Guarda el resultado en una variable llamada `dia_semana_mas_ventas_por_centro`. 

El tipo de `dia_semana_mas_ventas_por_centro` debe ser `pandas.core.series.Series` donde las etiquetas deben ser el nombre de los centros comerciales y los valores deben ser el nombre del dia de la semana con mas ventas.

In [27]:
datos["invoice_date"]= pd.to_datetime(datos["invoice_date"],errors="coerce")
datos["dia_semana"]= datos["invoice_date"].dt.day_name()
conteo_ventas= datos.groupby(["shopping_mall", "dia_semana"]).size()

dia_semana_mas_ventas_por_centro = conteo_ventas.groupby('shopping_mall').idxmax()
print(dia_semana_mas_ventas_por_centro)

shopping_mall
Cevahir AVM                (Cevahir AVM, Friday)
Emaar Square Mall    (Emaar Square Mall, Friday)
Forum Istanbul        (Forum Istanbul, Thursday)
Istinye Park              (Istinye Park, Monday)
Kanyon                        (Kanyon, Saturday)
Mall of Istanbul      (Mall of Istanbul, Friday)
Metrocity                    (Metrocity, Monday)
Metropol AVM              (Metropol AVM, Friday)
Viaport Outlet        (Viaport Outlet, Saturday)
Zorlu Center           (Zorlu Center, Wednesday)
dtype: object

In [28]:
print(type(dia_semana_mas_ventas_por_centro))

<class 'pandas.core.series.Series'>